version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Analogy.LogViewer.Interfaces
    versions:
    - 2.10.2
    - 2.11.0
  - dependency-name: Analogy.LogViewer.gRPC
    versions:
    - 1.5.4.4
  - dependency-name: Analogy.LogViewer.RegexParser
    versions:
    - 1.8.1.3
  - dependency-name: Analogy.LogViewer.Template
    versions:
    - 1.8.1.3
